### PR TITLE
Add SmartR plugin.

### PR DESCRIPTION
**Pull request by PiotrZakrzewski**

### CODE REVIEW

**Comment by forus** [comment]
@PiotrZakrzewski Please resolve the conflicts.

**Comment by forus** [comment]
@PiotrZakrzewski Keep in mind that it's not enough to add SmartR to the repo xml file. You need to add SmartR to the transmartApp's build config as well. See https://github.com/thehyve/heim-transmartApp/blob/master/grails-app/conf/BuildConfig.groovy#L131

**Comment by PiotrZakrzewski** [comment]
Thanks. I know that, i added it in my fork and will push it later
Op 30 sep. 2015 18:22 schreef "forus" notifications@github.com:

**Comment by PiotrZakrzewski** [comment]
@forus conflict resolved

**Pull request merged**
